on:
  push:

name: Secret Leaks

jobs:
  trufflehog:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        extra_args: --results=verified,unknown
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
